
raw :
	clang -Wall -o exk \
\
add_nums.c \
compare_bins.c \
copy_num.c \
dub_abs.c \
full_adder.c \
full_sub.c \
init_nums.c \
loadNum.c \
main.c \
print_SHEFgrs.c \
printNumDetail.c \
proof.c \
shift_left_EHFgrs.c \
shift_left.c \
shift_right_EHFgrs.c \
shift_right.c