
raw :
	clang -Wall -o exec \
\
commonFunctions/checkOut.c \
commonFunctions/dateTimeStamp.c \
commonFunctions/timers.c \
\
resources/globalConstants.c \
resources/globalVariables.c \
\
testing/generators/makeNumbers.c \
testing/units/testBench.c \
testing/units/tu_dateTimeStamp.c \
testing/units/tu_makeNumbers.c \
testing/test_selector.c \
testing/testingConstants.c \
testing/waitEnterClear.c \
\
main.c

# -Weverything is bad, use -Wall
